// Generated by scripts/generate-seo.mjs before each production build.
// Configure the source values in seo.config.json or with deployment variables.
export const generatedSeoConfig = {
  "siteUrl": "",
  "googleSiteVerification": "",
  "publicRoutes": [
    "/"
  ],
  "business": {
    "name": "Remorquage Ben Arous",
    "description": "Service de remorquage automobile disponible 24h/24 et 7j/7 à Ben Arous, Mornag et dans le Grand Tunis.",
    "telephone": "+21621533933",
    "areaServed": [
      "Ben Arous",
      "Mornag",
      "Péage de Mornag",
      "Tunis",
      "Ariana",
      "Manouba"
    ],
    "address": null,
    "geo": null,
    "sameAs": []
  }
};
