import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const configPath = join(projectRoot, 'seo.config.json');
const generatedConfigPath = join(projectRoot, 'src', 'app', 'seo.generated.ts');
const sitemapPath = join(projectRoot, 'public', 'sitemap.xml');
const robotsPath = join(projectRoot, 'public', 'robots.txt');

const sourceConfig = JSON.parse(await readFile(configPath, 'utf8'));
const vercelProductionUrl = process.env['VERCEL_PROJECT_PRODUCTION_URL'];
const environmentSiteUrl = process.env['SEO_SITE_URL'];
const environmentVerification = process.env['GOOGLE_SITE_VERIFICATION'];

const candidateSiteUrl =
  environmentSiteUrl ||
  (vercelProductionUrl ? `https://${vercelProductionUrl}` : '') ||
  sourceConfig.siteUrl;
const siteUrl = candidateSiteUrl.replace(/\/$/, '');

if (siteUrl) {
  const parsedUrl = new URL(siteUrl);

  if (parsedUrl.protocol !== 'https:' || parsedUrl.pathname !== '/') {
    throw new Error(
      'SEO_SITE_URL/siteUrl must be an HTTPS origin without a path, for example https://www.your-domain.tn',
    );
  }
}

const generatedConfig = {
  ...sourceConfig,
  siteUrl,
  googleSiteVerification:
    environmentVerification || sourceConfig.googleSiteVerification,
};

const publicRoutes = [...new Set(sourceConfig.publicRoutes || ['/'])];

if (
  publicRoutes.length === 0 ||
  publicRoutes.some(
    (route) =>
      typeof route !== 'string' ||
      !route.startsWith('/') ||
      route.includes('?') ||
      route.includes('#'),
  )
) {
  throw new Error(
    'publicRoutes must contain clean paths that start with / and have no query string or fragment.',
  );
}

await writeFile(
  generatedConfigPath,
  `// Generated by scripts/generate-seo.mjs before each production build.\n` +
    `// Configure the source values in seo.config.json or with deployment variables.\n` +
    `export const generatedSeoConfig = ${JSON.stringify(generatedConfig, null, 2)};\n`,
  'utf8',
);

const sitemap = siteUrl
  ? `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${publicRoutes
  .map(
    (route) => `  <url>
    <loc>${escapeXml(`${siteUrl}${route}`)}</loc>
  </url>`,
  )
  .join('\n')}
</urlset>
`
  : `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Configure siteUrl in seo.config.json before publishing. -->
</urlset>
`;

const robots = `User-agent: *
Allow: /
${siteUrl ? `\nSitemap: ${siteUrl}/sitemap.xml\n` : ''}`;

await Promise.all([
  writeFile(sitemapPath, sitemap, 'utf8'),
  writeFile(robotsPath, robots, 'utf8'),
]);

if (siteUrl) {
  console.log(`SEO files generated for ${siteUrl}`);
} else {
  console.warn(
    'SEO site URL is not configured yet. The build remains valid, but canonical and sitemap URLs will be added only after siteUrl or SEO_SITE_URL is set.',
  );
}

function escapeXml(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}
